-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjRE+0Jj81OjonBzI
ENkLYE2E941TBTdIGSKkJhAdYJ2gCgYIKoZIzj0DAQehRANCAASLlKZ1/JnDlIcQ
/bYuT0R3dP1Y+Vw5Jqoks8eo1BzeTQuoEpdv+5qIr3kbiqU/gDvlczdGuFOwKGSJ
egtZzL6b
-----END PRIVATE KEY-----