require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'pursuitofhappiness' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  
  target 'pursuitofhappinessTests' do
    inherit! :complete
    # Pods for testing
  end
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'pursuitofhappiness-tvOS' do
  # Pods for pursuitofhappiness-tvOS

  target 'pursuitofhappiness-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
